database:
  hostname: "ws1.giacomobrotto.net"
  username: "gchristian_user"
  password: "Chr@291201"
  database: "gchristian_silexmc"
  port: 3306

messages:
  generals:
    no-player: "&4&lMONEY &8» &cThis player is not online at the moment."
    no-console: "&4&lMONEY &8» &cThis command can only be executed from player."
    no-permission: "&4&l» &cYou do not have permission for this command."
    no-subcommand: "&4&lMONEY &8» &cThis subcommand does not exist."
    no-correct-usage: "&4&lMONEY &8» &cUsage is: %command%."
  economy:
    balance: "&2&lMONEY &8» &aYou have %balance% &8(&a%balance_format%&8) &aof money."
    sent-payment: "&2&lMONEY &8» &a%money%$ has been sent to %player_name%."
    receive-payment: "&2&lMONEY &8» &a%money%$ has been received from %player_name%."
    not-enough-balance: "&4&lMONEY &8» &cYou don't have enough money for this."
    set-balance: "&2&lMONEY &8» &aYou set %player_name%'s money to %money%$."
    give-balance: "&2&lMONEY &8» &aYou added %money%$ to %player_name%'s money."
    take-balance: "&2&lMONEY &8» &aRemoved %money%$ from %player_name%'s money."