name: Economy
version: '${project.version}'
main: me.imjaxs.silexmc.economy.Economy
authors: [ ImJaxs ]
softdepend:
  - PlaceholderAPI
commands:
  economy:
    description: //
    aliases:
      - eco
  balance:
    description: //
    aliases: []
  payment:
    description: //
    aliases:
      - pay